/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'berinle' at '11/11/14 6:15 AM' with Gradle 2.2
 *
 * @author berinle, @date 11/11/14 6:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
